name: Download Debian 12 Cloud TAR.XZ

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        run: mkdir -p images

      - name: Download into images/
        run: curl -Lo images/debian-12-genericcloud-amd64.tar.xz \
          https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.tar.xz

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: debian12-cloud
          files: images/debian-12-genericcloud-amd64.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
